### ISSUE TITLE
How to configure routing with config.yaml?

### ISSUE THREAD

**Issue by kahnesaaron** [vertexvaar/fal_gallery#11]
Could you @vertexvaar give a code example how i have to configure the config.yaml to use the typo3 9 routing?
at the moment i have this. 
```
routeEnhancers:
  GalleryList:
    type: Plugin
    limitToPages: [19]
    namespace: 'tx_falgallery_pi1'
    routePath: '/seite/{listPage}/'
    requirements:
      listPage: '[0-9]{1..3}'
```
but this isnt working right.
